# /etc/raspotify/conf -- Raspotify configuration

# Device name shown in Spotify Connect
DEVICE_NAME="Boombox"

# ALSA device for audio output
BACKEND_ARGS="--device pcm.spotify"

# Bitrate (96, 160, 320)
BITRATE="320"
